---
inherit_from:
  - https://bitbucket.org/rabidtech/rabid-dotfiles/raw/master/.rubocop.yml
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*

Style/FileName:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'

Style/FrozenStringLiteralComment:
  Enabled: false
